# Generated by Django 3.2.4 on 2021-06-24 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasketGenre', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=900)),
                ('url', models.CharField(max_length=200)),
                ('Num', models.IntegerField()),
                ('poster', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=900, null=True)),
                ('poster', models.CharField(max_length=900)),
                ('url', models.CharField(max_length=200)),
                ('BasketGenre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.basket', verbose_name='basket')),
            ],
        ),
    ]
