# Generated by Django 3.2.4 on 2021-06-18 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 0, 6, 56, 534638), verbose_name='date created'),
        ),
    ]
