# Generated by Django 3.2.4 on 2021-06-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='BasketGenre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.basket', verbose_name='basket'),
        ),
    ]
